# GitHub Pages Configuration for Dynamic Codex
title: "⧬✶⧬ Codex Nexus - Living Knowledge Sovereignty Architecture"
description: "Revolutionary mathematical research platform with dynamic database integration"
url: "https://mikaeltheoret.github.io"
baseurl: "/Scroll-Protocol-Invocation"

# Theme settings
theme: minima
markdown: kramdown
highlighter: rouge

# Enable GitHub Pages features
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom navigation
header_pages:
  - index.html
  - prime-engine.html
  - data-upload.html
  - validation-dashboard.html

# SEO and metadata
author:
  name: "Mikael Theoret"
  email: "codex@nexus.eth"

social:
  name: "Codex Nexus"
  links:
    - "https://github.com/MikaelTHEoret/Scroll-Protocol-Invocation"

# Analytics and tracking
google_analytics: # Add your GA4 ID here if desired

# Custom variables
codex:
  version: "1.0.0"
  status: "active"
  last_update: "2025-06-01"
  components:
    - "Dynamic Database Integration"
    - "Real-time Validation Dashboard"
    - "Interactive Prime Prediction Engine"
    - "Automated CSV Processing"
    - "Live Visualization Platform"